//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrRobotDriver
{
    [Serializable]
    public class velocityServiceRequest : Message
    {
        public const string k_RosMessageName = "ur_robot_driver/velocityService";
        public override string RosMessageName => k_RosMessageName;

        public MoveitJointsMsg joints_input;
        public MoveitJointsMsg velocity_input;
        public Geometry.PoseMsg target_pose;

        public velocityServiceRequest()
        {
            this.joints_input = new MoveitJointsMsg();
            this.velocity_input = new MoveitJointsMsg();
            this.target_pose = new Geometry.PoseMsg();
        }

        public velocityServiceRequest(MoveitJointsMsg joints_input, MoveitJointsMsg velocity_input, Geometry.PoseMsg target_pose)
        {
            this.joints_input = joints_input;
            this.velocity_input = velocity_input;
            this.target_pose = target_pose;
        }

        public static velocityServiceRequest Deserialize(MessageDeserializer deserializer) => new velocityServiceRequest(deserializer);

        private velocityServiceRequest(MessageDeserializer deserializer)
        {
            this.joints_input = MoveitJointsMsg.Deserialize(deserializer);
            this.velocity_input = MoveitJointsMsg.Deserialize(deserializer);
            this.target_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints_input);
            serializer.Write(this.velocity_input);
            serializer.Write(this.target_pose);
        }

        public override string ToString()
        {
            return "velocityServiceRequest: " +
            "\njoints_input: " + joints_input.ToString() +
            "\nvelocity_input: " + velocity_input.ToString() +
            "\ntarget_pose: " + target_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
