//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrRobotDriver
{
    [Serializable]
    public class velocityServiceResponse : Message
    {
        public const string k_RosMessageName = "ur_robot_driver/velocityService";
        public override string RosMessageName => k_RosMessageName;

        public MoveitJointsMsg velocity_output;

        public velocityServiceResponse()
        {
            this.velocity_output = new MoveitJointsMsg();
        }

        public velocityServiceResponse(MoveitJointsMsg velocity_output)
        {
            this.velocity_output = velocity_output;
        }

        public static velocityServiceResponse Deserialize(MessageDeserializer deserializer) => new velocityServiceResponse(deserializer);

        private velocityServiceResponse(MessageDeserializer deserializer)
        {
            this.velocity_output = MoveitJointsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.velocity_output);
        }

        public override string ToString()
        {
            return "velocityServiceResponse: " +
            "\nvelocity_output: " + velocity_output.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
